fix: [#72] Adds translation on the location views
open-y-subprojects/openy_map pull request #74
Opened 2024-04-03 19:22 UTC by andrebonon

2024-04-05 07:01 UTC, podarok commented
@andrebonon we should write hook_update_N and update/install configs/config parameters for existing sites during upgrade

2024-05-03 18:32 UTC, andrebonon commented
@podarok please check the last addition.

2024-05-06 09:55 UTC, podarok commented on openy_map.install
> +  $config_storage->write('views.view.locations', $source->read('views.view.locations'));
please, use config updater @andrebonon https://github.com/open-y-subprojects/openy_map/pull/74/files#diff-f5f5f7f0a35898108deac0ddd5770f86a2910ef5c8f0be5ac7fb7b499d5d6804R118

config write not always run proper subscriber, and not all of the,m

2024-05-06 09:55 UTC, podarok requested changes
needs https://github.com/open-y-subprojects/openy_map/pull/74/files#diff-f5f5f7f0a35898108deac0ddd5770f86a2910ef5c8f0be5ac7fb7b499d5d6804R118 instead of config write, please

2024-05-08 07:35 UTC, podarok commented on openy_map.info.yml
>  version: 1.15
```suggestion
version: 5.1.1
```

2024-05-08 07:36 UTC, merged