Filter pins by current language
open-y-subprojects/openy_map pull request #78
Opened 2024-04-10 15:06 UTC by froboy

requires https://github.com/open-y-subprojects/openy_custom/pull/70

2024-04-10 15:27 UTC, andrebonon approved these changes

2024-04-11 12:02 UTC, podarok requested changes

2024-04-11 12:02 UTC, podarok commented on src/OpenyMapDataWrapper.php
> +        ->condition('langcode', $langcode)
what happens with `und` ? @froboy

2024-04-30 18:31 UTC, froboy commented on src/OpenyMapDataWrapper.php
> +        ->condition('langcode', $langcode)
See comment https://github.com/open-y-subprojects/openy_custom/pull/70#discussion_r1585311655

2024-05-01 07:04 UTC, merged